/**
 * What this service is, and what it is doing right now.
 *
 * Figures come from the operator's own `service_status`, so this page reports
 * the running deployment rather than what the repository claims about it.
 *
 * Every word here that is jargon carries its own definition on a dotted
 * underline (see `lib/glossary`). The page has to say MCP, Nostr, satoshi and
 * serverless to be truthful, and each of them is a wall to somebody who came
 * for a game about bees.
 */

import { useEffect, useState } from "react";
import { annotate } from "../lib/glossary.tsx";
import { serviceStatus } from "../lib/mcp";

/** One paragraph, with the jargon in it explained. */
function P({ text, seen, className = "" }: { text: string; seen: Set<string>; className?: string }) {
  return <p className={`text-[15px] text-ink/90 ${className}`}>{annotate(text, seen)}</p>;
}

const HOW = [
  [
    "It is tools, not screens",
    "Every motion is a named tool call on an MCP server, so an agent plays it exactly as this " +
      "page does — same calls, same prices, same rules. The interface is one client among " +
      "several, not the game.",
  ],
  [
    "It can be played blind",
    "Nothing about a move requires seeing it. The board comes back as data — which cells are " +
      "open, where every bee stands, whose turn has come round — so a program with no screen " +
      "competes on equal terms. The simulated bees that fill a thin hive are exactly that.",
  ],
  [
    "The service remembers nothing",
    "It is stateless. Every board, bee and fare lives in serverless Postgres, and each request " +
      "reads it fresh, so two calls a second apart can land on two different machines and " +
      "neither can tell. Between rounds the whole thing costs nothing to keep running.",
  ],
  [
    "The state is shared, and contended",
    "Fifty bees writing to one board is the hard part. Every move is a single fenced statement " +
      "that either wins the cell or does not — no locks, no transaction, and no way for two " +
      "bees to occupy the same cell because both were told they could.",
  ],
  [
    "Your name is a key",
    "Identity is a Nostr npub, generated by you and proven by a signature. There is no account " +
      "to create, no password to lose, and no KYC — a key is enough to play.",
  ],
  [
    "Money is bitcoin, and it moves",
    "Fares are satoshis from a balance you top up in advance. The pot is split when a round " +
      "settles and paid over Lightning: to the beneficiary, and to a winner who chose to keep " +
      "their share rather than donate it.",
  ],
  [
    "The hives are kept warm on demand",
    "A scheduled service seats simulated bees when a hive is thin, so somebody who arrives " +
      "alone still gets a race. They hold their own keys, pay their own fares, and play through " +
      "the same public tools as anyone else — they are opponents, not scenery.",
  ],
];

export default function About() {
  const [status, setStatus] = useState<Record<string, unknown> | null>(null);
  // One page, one pass: a term is marked the first time it appears and left
  // alone after that. Six dotted underlines of "MCP" reads as spam.
  const seen = new Set<string>();

  useEffect(() => {
    let alive = true;
    serviceStatus()
      .then((s) => alive && setStatus(s as Record<string, unknown>))
      .catch(() => undefined);
    return () => {
      alive = false;
    };
  }, []);

  const rows: [string, string][] = status
    ? [
        ["Service", String(status.service ?? "—")],
        ["Version", String(status.version ?? "—")],
        ["Tollbooth SDK", String(status.tollbooth_dpyc_version ?? "—")],
        ["Persistence", status.vault_configured ? "configured" : "not configured"],
      ]
    : [];

  return (
    <div className="mx-auto max-w-2xl px-5 py-8 leading-relaxed">
      <h1 className="text-2xl font-semibold tracking-tight">About</h1>

      <P
        seen={seen}
        className="mt-4"
        text={
          "The Bee's Knees is an MCP service on the DPYC network. Every motion your bee makes " +
          "is a tool call priced by the operator, paid from a pre-funded balance in satoshis — " +
          "no accounts, no card, no interruption mid-match. Your identity is a Nostr key, not " +
          "an email address."
        }
      />

      <P
        seen={seen}
        className="mt-4"
        text={
          "Because it is an MCP service, an AI agent can play it as readily as a browser can. " +
          "The board, the rules and the clock all live on the server; a client only asks what " +
          "the board looks like and says what it wants to do next."
        }
      />

      <p className="mt-4 text-[13px] text-ink/65">
        Underlined words carry a short definition — hover one, or tap it on a touch screen.
      </p>

      <h2 className="mt-8 text-sm font-semibold text-ink/90">This deployment</h2>
      <dl className="mt-3 divide-y divide-ink/10 rounded-xl bg-ink/4 text-sm">
        {rows.length ? (
          rows.map(([k, v]) => (
            <div key={k} className="flex justify-between px-4 py-2.5">
              <dt className="text-ink/70">{k}</dt>
              <dd className="font-mono text-[12px]">{v}</dd>
            </div>
          ))
        ) : (
          <div className="px-4 py-2.5 text-ink/65">Asking the hive…</div>
        )}
      </dl>

      <h2 className="mt-8 text-sm font-semibold text-ink/90">The board</h2>
      <P
        seen={seen}
        className="mt-2"
        text={
          "A hive is a ring of cells that narrows toward its queen — the wall holds about " +
          "fifty, the last ring before the chamber holds six. Everyone starts spread around the " +
          "outside and converges. Cutting fresh comb is slow and opens the way for everyone " +
          "behind you; riding a shaft somebody else paid for is fast, and they can bring it " +
          "down on you."
        }
      />
      <P
        seen={seen}
        className="mt-3"
        text={
          "A bee acts once per cooldown, measured on the clock, so no amount of spending buys a " +
          "faster bee. What spending buys is interference."
        }
      />

      <h2 className="mt-8 text-sm font-semibold text-ink/90">How it is built</h2>
      <p className="mt-2 text-[15px] text-ink/90">
        A game is an unkind thing to build this way — shared state, many writers, and a second is
        a long time. That is most of why it is worth building.
      </p>
      <dl className="mt-4 space-y-4">
        {HOW.map(([title, body]) => (
          <div key={title}>
            <dt className="text-[15px] font-semibold text-ink/90">{title}</dt>
            <dd className="mt-1 text-[15px] text-ink/78">{annotate(body, seen)}</dd>
          </div>
        ))}
      </dl>

      <p className="mt-8 text-xs text-ink/65">
        Five hives run at once with twelve seats each, and a match begins as soon as any hive
        holds its quorum of eight bees. Five rather than one because a race between sixty
        near-identical bees to a single queen is decided by variance rather than by skill — the
        split is measured, not a matter of taste.
      </p>
    </div>
  );
}
